"""
compute_rl.py
Computes every root-locus quantity analytically, then writes root_locus.asy
with all numeric values embedded so Asymptote only has to draw.

G(s)H(s) = k(s^2 - 2s + 5) / (s^2 + 1.5s - 1)
"""

import numpy as np
import control
import textwrap

# ── System definition ────────────────────────────────────────────────────────
num = [1, -2,  5]     # s^2 - 2s + 5
den = [1, 1.5, -1]    # s^2 + 1.5s - 1
sys = control.tf(num, den)

# ── Poles & zeros ─────────────────────────────────────────────────────────────
poles = np.roots(den)   # real
zeros = np.roots(num)   # complex conjugate pair

# ── Breakaway point ──────────────────────────────────────────────────────────
# d/ds[den(s)/num(s)] = 0  →  den'·num - den·num' = 0
char_poly = np.polysub(np.polymul(np.polyder(den), num),
                       np.polymul(den, np.polyder(num)))
bp_candidates = np.roots(char_poly)

def K_at(s):
    return -np.polyval(den, s) / np.polyval(num, s)

breakaways = [(s.real, K_at(s.real).real)
              for s in bp_candidates
              if abs(s.imag) < 1e-8 and K_at(s.real).real >= -1e-10]
bp_s, bp_K = breakaways[0]   # the one between the two poles

# ── jω-axis crossing (Routh) ──────────────────────────────────────────────────
# Closed-loop: (1+k)s^2 + (1.5 - 2k)s + (5k - 1) = 0
# Imag: (1.5 - 2k) = 0  →  k = 0.75
# Real: ω^2 = (5k-1)/(1+k)
k_jw  = 0.75
w_jw  = float(np.sqrt((5*k_jw - 1) / (1 + k_jw)))

# ── Arrival angles at complex zeros ──────────────────────────────────────────
def arrival_angle(z, poles, zeros):
    angle_p = sum(np.angle(z - p) for p in poles)
    angle_z = sum(np.angle(z - ze) for ze in zeros if not np.isclose(ze, z))
    return np.pi - angle_p + angle_z      # (2·0+1)π condition

arr_top = np.degrees(arrival_angle(zeros[0], poles, zeros))
arr_bot = np.degrees(arrival_angle(zeros[1], poles, zeros))

# ── Root locus branch points over fine K range ───────────────────────────────
k_range = np.concatenate([
    np.linspace(0,    0.005, 300),
    np.linspace(0.005, 0.24, 600),
    np.linspace(0.24,  0.75, 600),
    np.linspace(0.75,  8.0, 600),
])
rlist, _ = control.root_locus(sys, kvect=k_range, plot=False)

# rlist: (N, n_poles) – sort columns so branch 0 starts from pole[0]=0.5
#  and branch 1 starts from pole[1]=-2
branch0 = rlist[:, np.argmin(np.abs(rlist[0] - poles[0]))]
branch1 = rlist[:, np.argmin(np.abs(rlist[0] - poles[1]))]

def asy_pairs(branch, max_pts=160):
    """Down-sample to ~max_pts evenly spaced points, return Asymptote pair[] literal."""
    idx = np.round(np.linspace(0, len(branch)-1, max_pts)).astype(int)
    pts = branch[idx]
    inner = ",\n    ".join(f"({p.real:.6f},{p.imag:.6f})" for p in pts)
    return "{" + inner + "}"

b0_str = asy_pairs(branch0)
b1_str = asy_pairs(branch1)

# ── Print summary ─────────────────────────────────────────────────────────────
print("="*60)
print(f"Poles          : {poles}")
print(f"Zeros          : {zeros}")
print(f"Breakaway      : s = {bp_s:.5f},  K = {bp_K:.5f}")
print(f"jω-crossing    : K = {k_jw},  ω = ±{w_jw:.5f}")
print(f"Arrival angle+ : {arr_top:.2f}°")
print(f"Arrival angle- : {arr_bot:.2f}°")
print(f"Asymptotes     : none  (n−m = 0)")
print("="*60)

# ── Write Asymptote file ──────────────────────────────────────────────────────
p0r, p0i = poles[0].real, poles[0].imag   #  0.5
p1r, p1i = poles[1].real, poles[1].imag   # -2.0
z0r, z0i = zeros[0].real, zeros[0].imag   #  1, +2
z1r, z1i = zeros[1].real, zeros[1].imag   #  1, -2

asy_src = f"""\
// ─────────────────────────────────────────────────────────────────────────────
// root_locus.asy   —   ALL NUMERIC VALUES GENERATED BY compute_rl.py
// G(s)H(s) = k(s^2 - 2s + 5) / (s^2 + 1.5s - 1)
// ─────────────────────────────────────────────────────────────────────────────
import graph;
usepackage("amsmath");
size(520, 520);

// ── Computed values (Python) ─────────────────────────────────────────────────
pair pole0  = ({p0r:.6f}, {p0i:.6f});   // s = +0.5
pair pole1  = ({p1r:.6f}, {p1i:.6f});   // s = -2.0
pair zero0  = ({z0r:.6f}, {z0i:.6f});   // s = 1+2j
pair zero1  = ({z1r:.6f}, {z1i:.6f});   // s = 1-2j
pair bkaway = ({bp_s:.6f}, 0);           // breakaway s ≈ {bp_s:.4f}
real bkaway_K = {bp_K:.6f};
real jw_K     = {k_jw:.6f};             // jω-crossing gain
real jw_w     = {w_jw:.6f};             // jω-crossing frequency
real arr_top  = {arr_top:.4f};          // arrival angle at zero0 (deg)
real arr_bot  = {arr_bot:.4f};          // arrival angle at zero1 (deg)

// Branch sample points (Python-computed root-locus)
pair[] br0 = {b0_str};
pair[] br1 = {b1_str};

// ── Canvas limits ────────────────────────────────────────────────────────────
real xmin=-3.5, xmax=2.8, ymin=-3.2, ymax=3.2;

// ── Grid ─────────────────────────────────────────────────────────────────────
pen gridpen = gray(0.82) + linewidth(0.25);
for (int i=(int)xmin; i<=(int)xmax; ++i)
    draw((i,ymin)--(i,ymax), gridpen);
for (int j=(int)ymin; j<=(int)ymax; ++j)
    draw((xmin,j)--(xmax,j), gridpen);

// ── Axes ──────────────────────────────────────────────────────────────────────
draw((xmin,0)--(xmax,0), black, Arrow(TeXHead));
draw((0,ymin)--(0,ymax), black, Arrow(TeXHead));
label("$\\sigma$",       (xmax+0.05, 0),      SE, fontsize(11pt));
label("$j\\omega$",      (0,          ymax+0.05), NE, fontsize(11pt));

// Tick marks + numeric labels
for (int i=(int)xmin; i<=(int)xmax; ++i) {{
    if (i==0) continue;
    draw((i,-0.09)--(i,0.09), black);
    label("$"+format("%d",i)+"$", (i,-0.08), S, fontsize(7pt));
}}
for (int j=(int)ymin; j<=(int)ymax; ++j) {{
    if (j==0) continue;
    draw((-0.09,j)--(0.09,j), black);
    label("$"+format("%d",j)+"j$", (-0.08,j), W, fontsize(7pt));
}}
label("$0$", (0.1,-0.22), fontsize(7pt));

// ── Root locus branches ───────────────────────────────────────────────────────
pen branchpen = rgb(0.1,0.35,0.75) + linewidth(2.0);

guide g0, g1;
for (int i=0; i<br0.length; ++i) g0 = g0..br0[i];
for (int i=0; i<br1.length; ++i) g1 = g1..br1[i];
draw(g0, branchpen);
draw(g1, branchpen);

// Direction arrows at mid-branch
int mid = (int)(br0.length/2);
draw(br0[mid-1]--br0[mid+1], branchpen, MidArrow(TeXHead, 1.2));
draw(br1[mid-1]--br1[mid+1], branchpen, MidArrow(TeXHead, 1.2));

// ── Real-axis locus segment ───────────────────────────────────────────────────
// Shaded band: [pole1, pole0] on real axis
filldraw(box(({p1r:.4f},-0.06),({p0r:.4f},0.06)),
         rgb(0.1,0.35,0.75)+opacity(0.15),
         rgb(0.1,0.35,0.75)+opacity(0.4)+linewidth(0.4));

// ── jω-axis crossing markers ──────────────────────────────────────────────────
pen jwpen = rgb(0.85,0.33,0.0) + linewidth(2.2);
real s = 0.18;  // star arm half-size
for (real ang=0; ang<360; ang+=60) {{
    real a = ang*pi/180;
    draw((-s*cos(a), jw_w - s*sin(a))--(s*cos(a), jw_w + s*sin(a)), jwpen);
    draw((-s*cos(a),-jw_w - s*sin(a))--(s*cos(a),-jw_w + s*sin(a)), jwpen);
}}
label("$j\\omega$-cross: $K={k_jw:.3f}$, $\\omega={{\\pm}}{w_jw:.3f}$",
      (0.25, jw_w+0.35), E, fontsize(8pt)+rgb(0.85,0.33,0.0));

// ── Poles  ×  ────────────────────────────────────────────────────────────────
pen polepen = rgb(0.78,0.1,0.1) + linewidth(2.8);
real d = 0.14;
draw((pole0.x-d, pole0.y-d)--(pole0.x+d, pole0.y+d), polepen);
draw((pole0.x-d, pole0.y+d)--(pole0.x+d, pole0.y-d), polepen);
draw((pole1.x-d, pole1.y-d)--(pole1.x+d, pole1.y+d), polepen);
draw((pole1.x-d, pole1.y+d)--(pole1.x+d, pole1.y-d), polepen);
label("$s={p0r:.1f}$", pole0+(0.15, 0.28), fontsize(8.5pt)+rgb(0.78,0.1,0.1));
label("$s={p1r:.1f}$", pole1+(0.15, 0.28), fontsize(8.5pt)+rgb(0.78,0.1,0.1));

// ── Zeros  ○  ────────────────────────────────────────────────────────────────
pen zeropen = rgb(0.05,0.45,0.1) + linewidth(2.5);
draw(circle(zero0, 0.14), zeropen);
draw(circle(zero1, 0.14), zeropen);
label("$s=1+2j$", zero0+(0.22, 0.28), fontsize(8.5pt)+rgb(0.05,0.45,0.1));
label("$s=1-2j$", zero1+(0.22,-0.28), fontsize(8.5pt)+rgb(0.05,0.45,0.1));

// ── Breakaway point  ◆  ───────────────────────────────────────────────────────
pen bkpen = rgb(0.42,0.0,0.65) + linewidth(2.2);
real db = 0.12;
filldraw(shift(bkaway)*scale(db)*rotate(45)*unitsquare,
         rgb(0.42,0.0,0.65), bkpen);
label("Breakaway: $s\\approx{bp_s:.4f}$, $K={bp_K:.4f}$",
      bkaway+(-0.1, -0.38), S, fontsize(8pt)+rgb(0.42,0.0,0.65));

// ── Legend (bottom-left) ───────────────────────────────────────────────────────
real lx=-3.38, ly=-2.3, ls=0.55, lg=0.42;
draw((lx,ly)--(lx+ls,ly), branchpen);
label("Root locus branch",     (lx+ls+0.08, ly),      E, fontsize(8pt));
draw((lx-d,ly-lg-d)--(lx+d,ly-lg+d), polepen);
draw((lx-d,ly-lg+d)--(lx+d,ly-lg-d), polepen);
label("Open-loop pole",        (lx+ls+0.08, ly-lg),   E, fontsize(8pt));
draw(circle((lx+ls/2,ly-2lg), 0.11), zeropen);
label("Open-loop zero",        (lx+ls+0.08, ly-2lg),  E, fontsize(8pt));

// ── Title ─────────────────────────────────────────────────────────────────────
label("Root Locus $\\displaystyle G(s)H(s)=\\dfrac{{k(s^2-2s+5)}}{{s^2+1.5s-1}}$",
      (0, -3.0), fontsize(11pt));
label("Poles: $s=-2,\\,0.5$\\quad Zeros: $s=1\\pm2j$\\quad $(n=m=2$, no asymptotes$)$",
      (0, -3.55), fontsize(8.5pt)+gray(0.3));
"""

out_path = "root_locus.asy"
with open(out_path, "w", encoding="utf-8") as f:
    f.write(asy_src)

print(f"\n✓  Written: {out_path}")